Add theme as a locator predicate
mvysny/karibu-testing pull request #112
Opened 2022-05-20 09:35 UTC by caalador

Enable using theme as a search predicate in locator

2022-05-20 09:42 UTC, mvysny requested changes

2022-05-20 09:42 UTC, mvysny commented on karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/Locator.kt
> +        public var predicates: MutableList<Predicate<T>> = mutableListOf(),
Awesome idea, thank you :+1: 2 things to fix please:
1. The `var themes` is missing the `public` keyword, to stress that it's a public API
2. The `predicates` list should be the last one, to stress that it's a list of custom stuff of lower importance.

2022-05-20 09:47 UTC, caalador commented on karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/Locator.kt
> +        public var predicates: MutableList<Predicate<T>> = mutableListOf(),
done, This actually came from Knoobie to the TB project

2022-05-20 09:48 UTC, mvysny approved these changes

2022-06-06 11:22 UTC, mvysny commented
@caalador the tests seem to be failing. Could you investigate please?

2022-06-06 11:40 UTC, caalador commented
Helps to actually check against the values also.

2022-06-06 12:08 UTC, mvysny approved these changes
looks good, thank you

2022-06-06 12:09 UTC, merged