find components inside virtual children
mvysny/karibu-testing pull request #86
Opened 2021-07-30 12:59 UTC by hfazai

Fixes #85

2021-07-30 13:46 UTC, mvysny requested changes
Could you please also write a test that actually instantiates the EnhancedDialog and makes sure that the necessary components are discovered? Please go ahead and add the EnhancedDialog dependency to the karibu-testing test suite, since the test suite is private to Karibu-Testing and not exposed to the client projects.

2021-07-30 13:46 UTC, mvysny commented on karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/ElementUtils.kt
> +        if(it.element.parent == this) {
I think you can skip this check - even though ComponentUtil.findComponents() uses recursion, it won't go through elements with components attached, and therefore it will find the closest components properly.

2021-07-30 13:46 UTC, mvysny commented on karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/BasicUtils.kt
> +        if (child.component.isPresent) {
You can safely skip this check: if the element has a component linked, the _findComponents() on that element will only return that single component.

2021-07-30 20:02 UTC, hfazai commented
Duplicated elements has apeared from virtual children. Let's see the tree for this example:

Before descovering virtual children:  (ModuleListMenu is a MenuBar)
![image](https://user-images.githubusercontent.com/57005249/127685001-ccdeb1ff-b865-4856-a07d-b30b88726e85.png)

After (New element apeared is marked in red)
![ss](https://user-images.githubusercontent.com/57005249/127687571-b64946e0-2409-41d8-b002-8020fe62acd5.png)

for menubar and grid, It seems that items are added to children and virtual children.

I did a [change](https://github.com/mvysny/karibu-testing/pull/86/commits/a097a40fb2ac1893346e422a090915f60a96570e) to keep only components discovered in virtual children. This way, some PrettyPrintTree tests are failing because the tree graph has changed. (in the example above we keep only the red component)
If you agree with these changes, I will change the expected trees to get all tests passing.

2021-08-02 13:46 UTC, mvysny commented
Gotcha, thanks! The problem is that when I try to comment out the `component is MenuItemBase<*, *, *> -> {` rule, the sub menu items are no longer discovered properly.

I propose to "revert" the behavior for MenuItemBase and for MenuBar and for Grid.

I've tested with this `getAllChildren()` implementation and it seems to be working properly:

```
    public fun getAllChildren(component: Component): List<Component> = when {
        component is Grid<*> -> {
            // don't attach the header/footer components as a child of the Column component:
            // that would make components in merged cells appear more than once.
            // see https://github.com/mvysny/karibu-testing/issues/52
            val headerComponents: List<Component> = component.headerRows
                    .flatMap { it.cells.map { it.component } }
                    .filterNotNull()
            val footerComponents: List<Component> = component.footerRows
                    .flatMap { it.cells.map { it.component } }
                    .filterNotNull()
            val editorComponents: List<Component> = component.columns
                    .mapNotNull { it.editorComponent }
            val children = component.children.toList()
            (headerComponents + footerComponents + editorComponents + children).distinct()
        }
        component is MenuItemBase<*, *, *> -> {
            // also include component.children: https://github.com/mvysny/karibu-testing/issues/76
            (component.children.toList() + component.subMenu.items).distinct()
        }
        component is MenuBar -> {
            // don't include virtual children since that would make the MenuItems appear two times.
            component.children.toList()
        }
        component is PolymerTemplate<*> -> {
            // don't include virtual children since those will include nested components.
            // however, those components are only they are only "shallow shells" of components constructed
            // server-side - almost none of their properties are transferred to the server-side.
            // Listing those components with null captions and other properties would only be confusing.
            // Therefore, let's leave the virtual children out for now.
            // See https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#polymer-templates--lit-templates
            component.children.toList()
        }
        component.javaClass.name == "com.vaadin.flow.component.grid.ColumnGroup" -> {
            // don't include virtual children since that would include the header/footer components
            // which would clash with Grid.Column later on
            component.children.toList()
        }
        component is Grid.Column<*> -> {
            // don't include virtual children since that would include the header/footer components
            // which would clash with Grid.Column later on
            component.children.toList()
        }
        // Also include virtual children.
        // Issue: https://github.com/mvysny/karibu-testing/issues/85
        else -> component._allChildren
    }
```
what do you think?

2021-08-02 15:45 UTC, hfazai commented
Oh thanks! I think this is the best way to do it.

I would like to add unit tests for EnhancedDialog. If want to merge this PR now, I'll do it in another PR.

2021-08-02 15:54 UTC, mvysny commented
Please go ahead and add the tests in this PR, no problem

2021-08-02 16:51 UTC, hfazai commented
> Please go ahead and add the tests in this PR, no problem

Done :+1:

2021-08-03 06:51 UTC, mvysny approved these changes
Excellent work, thank you :+1:

2021-08-03 06:51 UTC, merged

2021-08-03 06:52 UTC, mvysny commented
I was planning to release next Karibu-Testing after Vaadin 21 is released, but if you need an earlier release just let me know :+1:

2021-08-03 08:01 UTC, hfazai commented
> I was planning to release next Karibu-Testing after Vaadin 21 is released, but if you need an earlier release just let me know

Ok, Thank you!
For now I'm overriding `getChildren()` and adding needed code untill I upgrade to the next release.

I'm building also a module based on Karibu-Testing that provides hight-level functions to test applications made with Galite (https://github.com/kopiLeft/Galite/tree/master/galite-testing). As galite is a framework to build applications made of forms, pages, reports, charts, triggers and commands...etc Galite-testing provides a functions to simulate user actions like (Form.open(), Command.trigger(), login(),..etc). The framework still under construction :smile: but it is now in an advanced steps.

2021-08-03 08:40 UTC, mvysny commented
Nice project, thanks for sharing :+1: I'll definitely take a look